name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening this issue. We will soon work on resolving this in the future releases.'
        pr-message: 'Thanks for actively contributing to this project. Someone will review and approve as soon as possible.'
